# Generated by Django 2.2 on 2019-04-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('department', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=40, unique=True)),
                ('branch_status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=40, unique=True)),
                ('department_status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=40)),
                ('designation_status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.DepartmentModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=40)),
                ('employee_name', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=40)),
                ('mother_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='emplyee_image/no-image.png', upload_to='emplyee_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.BranchModel')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.DepartmentModel')),
                ('designation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.DesignationModel')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQualificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_exam', models.CharField(max_length=40)),
                ('year_of_passing', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('document_file', models.ImageField(default='emplyee_document/no-image.png', upload_to='emplyee_document/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.EmployeePersonalModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePreviousworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('company_address', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.EmployeePersonalModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalbioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.ImageField(default='emplyee_document/no-image.png', upload_to='emplyee_document/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.EmployeePersonalModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJoiningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateTimeField()),
                ('offer_date', models.DateTimeField()),
                ('confirmation_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.EmployeePersonalModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=50)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.EmployeePersonalModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=40)),
                ('branch_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emplyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.EmployeePersonalModel')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.AttendanceModel')),
            ],
        ),
        migrations.CreateModel(
            name='AddLeaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=40)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.LeaveTypeModel')),
            ],
        ),
    ]
