# Generated by Django 2.2 on 2019-04-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeequalificationmodel',
            name='document_file',
        ),
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=40)),
                ('issue_date', models.DateTimeField()),
                ('previous_branch', models.CharField(max_length=60)),
                ('previous_department', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present_branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.BranchModel')),
                ('present_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.DepartmentModel')),
            ],
        ),
    ]
