# Generated by Django 2.2 on 2019-04-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190427_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalmodel',
            name='employee_code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
