# Generated by Django 2.2 on 2019-04-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190427_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.DepartmentModel'),
        ),
    ]
