# Generated by Django 2.1.7 on 2019-04-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190427_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalmodel',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
