# Generated by Django 2.2 on 2019-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190428_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechildmodel',
            name='status',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
