# Generated by Django 2.2 on 2019-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_attendancechildmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancechildmodel',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
