# Generated by Django 2.2 on 2019-04-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190428_1614'),
        ('backend', '0004_auto_20190428_1015'),
    ]

    operations = [
    ]
