# Generated by Django 2.2 on 2019-04-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190429_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalmodel',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
