# Generated by Django 2.2 on 2019-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190429_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=40)),
                ('company_address', models.TextField()),
            ],
        ),
    ]
